INSERT INTO GOT_CUST (ID,LOGINID,PARENT_ID,NAME,ISDEL,IS_ENABLE) VALUES (1,'admin',NULL,'默认用户','0','1');

INSERT INTO GOT_USER (ID,USER_ACCOUNT,PASSWORD,NAME,CUSTOMER_ID,ISDEL,IS_ENABLE) VALUES (1,'admin','nimda','系统管理员',1,'0','1');
